spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/weather_service_api_db"
    username: "postgres"
    password: "123"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


